export { EditorDetector }           from './ai/detector';
export { AICommandsManager }        from './ai/commands-manager';
export { AIToggleManager }          from './ai/toggle-manager';
export { TerminalManager }          from './terminal/side-panel';
export { GitResetManager }          from '../editor/git/reset-manager';
export { DebugManager }             from '../editor/debug/panel';
export { WordWrapManager }          from '../editor/wordwrap/manager';
export { PanelCommandsManager }     from '../notifications/panels/commands';
export { recoverSidePanelState }    from './terminal/startup-recovery';
